name: Fetch openHABian Docs

on:
  workflow_dispatch

jobs:
  fetchDocs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.0
        with:
          ref: final-stable

      - name: Checkout external repository
        uses: actions/checkout@v2.4.0
        with:
          repository: Luckenborg/doc_content_base
          path: '.external/openHABian'

      - name: Copy current docs contents
        run: |
          ls -ls ./installation
          rm -rf ./installation/openhabian*.md
          ls -ls ./installation
