name: Fetch openHABian Docs

on:
  workflow_dispatch

jobs:
  fetchDocs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.0
        with:
          ref: final-stable

      - name: Checkout external repository
        uses: actions/checkout@v2.4.0
        with:
          repository: Luckenborg/doc_content_base
          path: './external_contents/openHABian'

      - name: Check workspace contents
        run: |
          echo "List files and folders"
          echo "---"
          ls -ls
          echo "Find related files in the installation folder recursively"
          echo "---"
          find ./installation/
          echo "Print example doc."
          echo "---"
          cat ./installation/openhabian.md
          echo "---"

      - name: Remove existing doc contents
        run: find ./installation/ -iname "openhabian*" -type f -delete

      - name: Copy newest doc contents
        run: |
          echo "Copy current doc folder contents"
          cp -v ./external_contents/openHABian/docs/openhabian*.md ./installation
          cp -v ./external_contents/openHABian/docs/images/openHABian* ./installation/images

      - name: Check workspace contents
        run: |
          echo "List files and folders"
          echo "---"
          ls -ls
          echo "Find related files in the installation folder recursively"
          echo "---"
          find ./installation/
          echo "Print example doc."
          echo "---"
          cat ./installation/openhabian.md
          echo "---"

      - name: Remove external repositories
        run: rm -rf ./external

      - name: Check workspace contents
        run: ls -ls
      
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Automated openHABian Docs fetch
          commiter: openHAB Bot <info@openhab.org>
          author: openHAB Bot <info@openhab.org>
          branch: automated/fetch_openhabian_docs
          delete-branch: true
          title: "[Automated] Fetch openHABian docs"
          labels: |
            automated_pr
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
