name: Fetch openHABian Docs

on:
  workflow_dispatch

jobs:
  fetchDocs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.0
        with:
          ref: final-stable

      - name: Checkout external repository
        uses: actions/checkout@v2.4.0
        with:
          repository: Luckenborg/doc_content_base
          ref: main
          path: './.external/openHABian'

      - name: Check workspace contents
        run: ls -ls

      - name: Remove existing doc contents
        run: |
          echo "Remove existing openHABian doc files."
          find ./installation/ -iname "openhabian*" -type f -delete
          echo "---"
          echo "Check for remaining contents"
          echo "find ./installation/ -iname "openhabian*" -type f"
          find ./installation/ -iname "openhabian*" -type f
          echo "---"

      -name: Copy newest doc contents
        run: |
          echo "Copy current doc folder contents"
          cp -v ./.external/openHABian/docs/openhabian*.md ./installation
          cp -v ./.external/openHABian/docs/images/openHABian*.md ./installation/images
      
      -name: Remove external repositories
        run: rm -rf ./.external

      - name: Check workspace contents
        run: ls -ls
