name: Fetch openHABian Docs

on:
  workflow_dispatch:
  repository_dispatch:
    types: [update-openhabian-docs-event]

jobs:
  call-reusable-fetch-workflow:
    uses: ${{github.repository}}/.github/workflows/reusable-fetch.yml@main
    with:
      base_source_organization: Luckenborg
      base_source_repository: doc_content_base
      base_folder: installation
      doc_base_name: openhabian
      has_images: true
      image_base_name: openHABian
